### ISSUE TITLE
High RAM test fail with Diag264

### ISSUE THREAD

**Issue by BwanaFr** [BwanaFr/Fake7501#1]
See canceled merge request : [Nu7501](https://github.com/go4retro/Nu7501/pull/2)

**Comment by BwanaFr** [comment]
@robertgida Problem should be fixed in the actual commit.

**Comment by BwanaFr** [comment]
Another test with Diag264. Let the first memory test run, and it gives High memory OK. Then press the RESET button on machine!
Another test starts with chess board, etc, and High memory gives BAD. Something with the CPU reset imho...

**Comment by robertgida** [comment]
Yeah, I'm here to assist! :)

**Comment by BwanaFr** [comment]
@robertgida I moved my workplace, that's why I didn't give updates on this topic.
I pushed some changes on a ResetFix branch (https://github.com/BwanaFr/Fake7501/tree/ResetFix)
Please can you try it and let me know?

I'm not able to reproduce the issue on my side.
What computer do you use for testing? What's the speed grade of the Xilinx CPLD?

On my side, I use a PAL C16 upgraded to 64k and CPLD 7ns or 10ns.

Many thanks :)

**Comment by robertgida** [comment]
Hello, finally I had some time to test it. The latest ResetFix is seems OK on a Plus4 motherboard. I tested the two replacement cpus, one with new ResetFix fw, and the other with the older one, and definitely a success! After this, wrote the new firmware to the other CPU board and the memory test is without errors now! 
I'll have test with real environment, with games, SD2IEC, floppy drive, with demos, etc., even with full harness of Diag264 (which is in a cartridge for me). 
I tested an other Plus4 motherboard, and it seems, it has definitely some memory problems, regardless the cpu. It has 8 chips, each mT4264, the infamous one. I'll dig out all 8 memories and testing with my new toy just finished yesterday and I started to play: TEST EVERYTHING! :D 
this tool: Retro Chip Tester Professional: https://8bit-museum.de/sonstiges/hardware-projekte/hardware-projekte-chip-tester-english/

Btw, I using 10ns xilinx cpld-s.

**Comment by BwanaFr** [comment]
Hi,

Thanks for testing this new version :)

So, can I conclude it's now ok and merge the branch in master?

Many thanks, @robertgida!

**Comment by robertgida** [comment]
Yes, I tested with several games, and not found an issue yet.
Very important, don't use WDC65C02SP cpu. Preferred the original MOS6502, or other old 6502. The new WDC doesn't come with the illegal opcodes and several games, demos will not work.

**Comment by robertgida** [comment]
Hello again BwanaFr,
did you checked the similar Nu6510 project? I remade the PCB a while ago, but the code is not perfect.
https://github.com/go4retro/Nu6510

Br,
robertgida
